# Указываем явно, что это Python проект
providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    "/opt/venv/bin/pip install --upgrade pip",
    "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "EVENTLET_NO_GREENDNS=yes /opt/venv/bin/gunicorn wsgi:app --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT --timeout 180 --keep-alive 5"
