/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './templates/**/*.html',
    './templates/qa_tester/**/*.html',
    './templates/admin/**/*.html',
    './static/**/*.js',
    './app/theory/routes.py',
  ],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Golos Text"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      colors: {
        // Redirect legacy purple Tailwind classes to Indigo to maintain color harmony
        purple: {
          50:  '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          950: '#1e1b4b',
        },
        /* Airy Dark tokens — совпадает с boostudy2.0_examples/prepod/dark_mode*.html */
        dark: {
          bg:     '#07050A',
          card:   '#100E17',
          inner:  '#09070D',
          border: 'rgba(130, 90, 230, 0.12)',
          text:   '#F2EFFF',
          muted:  '#6A6480',
        },
        boo: {
          bg:           '#F5F7FA',
          surface:      '#FFFFFF',
          primary:      'var(--color-accent)',
          primaryHover: 'var(--color-accent-strong)',
          cyan:         '#06B6D4',
          cyanLight:    '#E0FDFE',
          coral:        '#FB7185',
          accent:       '#F59E0B',
          textMain:     '#1E293B',
          textMuted:    '#64748B',
        },
        // Semantic aliases used by component classes
        'bg-app':         'var(--color-bg-app)',
        'bg-surface':     'var(--color-bg-surface)',
        'bg-surface-alt': 'var(--color-bg-surface-alt)',
        'app':            'var(--color-bg-app)',
        'surface':        'var(--color-bg-surface)',
        'surface-alt':    'var(--color-bg-surface-alt)',
        accent: {
          DEFAULT: 'var(--color-accent)',
          strong:  'var(--color-accent-strong)',
          soft:    'var(--color-accent-soft)',
          on:      '#FFFFFF',
        },
        gamification: { DEFAULT: '#FBBF24', soft: '#FFFAE6' },
        success:      { DEFAULT: '#22D3EE', soft: '#ECFEFF' },
        error:        { DEFAULT: '#FB7185', soft: '#FFF1F5' },
        /* Оранжевый «зона риска» как в эталоне (orange-500), не amber #FBBF24 */
        warning:      { DEFAULT: '#F97316', soft: '#FFF7ED' },
        info:         { DEFAULT: '#8B5CF6', soft: '#EDE9FF' },
        'text-primary':   'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted':     'var(--color-text-muted)',
        'primary':        'var(--color-text-primary)',
        'secondary':      'var(--color-text-secondary)',
        'muted':          'var(--color-text-muted)',
        'text-inverse':   '#FFFFFF',
        stroke: {
          DEFAULT: 'var(--color-stroke)',
          strong:  'var(--color-stroke-strong)',
        },
      },
      borderRadius: {
        btn:       '16px',
        card:      '24px',
        'card-lg': '28px',
        '3xl':     '28px',
        '4xl':     '32px',
        pill:      '999px',
      },
      boxShadow: {
        'glass-dark':
          '0 4px 30px rgba(0, 0, 0, 0.5), inset 0 1px 0 rgba(255, 255, 255, 0.05)',
        'nav-dark':
          '0 10px 30px rgba(0, 0, 0, 0.6), inset 0 -1px 0 rgba(255, 255, 255, 0.05)',
        'neon-primary': '0 0 40px rgba(99, 102, 241, 0.2)',
        'neon-orange':  '0 0 20px rgba(249, 115, 22, 0.1)',
        'neon-red':     '0 0 20px rgba(251, 113, 133, 0.15)',
        tactile:       '0 8px 24px -4px rgba(15, 23, 42, 0.05)',
        'tactile-hover':'0 20px 40px -8px rgba(99, 102, 241, 0.15)',
        'ghost-glow':   '0 0 20px rgba(99, 102, 241, 0.3)',
        'purple-card':  '0 15px 30px -10px rgba(99, 102, 241, 0.4)',
        nav:           '0 4px 20px rgba(15, 23, 42, 0.05)',
        input:         'inset 0 2px 4px rgba(0, 0, 0, 0.02)',
        'inner-soft':  'inset 0 2px 10px rgba(0, 0, 0, 0.02)',
        sm:            '0 1px 3px rgba(15, 23, 42, 0.06)',
        // Legacy aliases
        soft:          '0 8px 24px -4px rgba(15, 23, 42, 0.05)',
        card:          '0 8px 24px -4px rgba(15, 23, 42, 0.05)',
        'card-hover':  '0 20px 40px -8px rgba(99, 102, 241, 0.15)',
        accent:        '0 8px 24px rgba(99, 102, 241, 0.20)',
        'accent-glow': '0 0 40px rgba(99, 102, 241, 0.15)',
        fab:           '0 6px 20px rgba(99, 102, 241, 0.25)',
        toast:         '0 10px 30px rgba(0, 0, 0, 0.12)',
        modal:         '0 20px 60px rgba(0, 0, 0, 0.15)',
      },
      animation: {
        'fade-in':     'fade-in 0.3s ease-out',
        'slide-up':    'slide-up 0.3s ease-out',
        'slide-down':  'slide-down 0.3s ease-out',
        'pulse-glow':  'pulse-glow 2s ease-in-out infinite',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-down': {
          from: { opacity: '0', transform: 'translateY(-12px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 12px rgba(123, 92, 255, 0.15)' },
          '50%':      { boxShadow: '0 0 24px rgba(123, 92, 255, 0.35)' },
        },
      },
    },
  },
  plugins: [],
};
